= BadAlgorithms

== Info

This is a small project I started for fun and to practise handling IntelliJ, Gradle,
Checkstyle, PMD and SpotBug (also trying to understand GitHub actions).

BadAlgorithms is a console application written in Java 11that executes various algorithms
like insertion sort, bubble sort and more. The user defines the list of elements that the
algorithms should act upon and can decide to get detailed output that describes the process
in depth.

== How to run

- Make sure you have installed the newest version of Java Runtime Environment.
- Download the version of BadAlgorithms that you want to use.
- Open a command line and navigate to the directory in which you saved the JAR file.
- Type 'java -jar BadAlgorithms.jar'. (If you saved the file under a different name, you
have to replace 'BadAlgorithms' with the new name.)

== Commands

|===
|Name |Effect

|help
|show a list of all commands

|end
|end the application

|list
|enter a list of integers for the algorithms to interact with

|show
|show the currently defined integer list

|verbose
|turn on/off the verbose setting, printing additional information while executing algorithms

|sel_sort
|sort your list with selection sort

|ins_sort
|sort your list with insertion sort

|bub_sort
|sort your list with bubble sort
|===


== Change log:

=== v0.0 - Initial state of the application (11/21/2020)

So far the user can input a list of integers and have them sorted with insertion sort,
bubble sort or selection sort.

There also is the 'verbose' option to generate detailed output of the algorithms actions.
